package au.edu.unsw.soacourse.dlvalidator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-30T21:10:45.239+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soacourse.unsw.edu.au/dlvalidator", name = "DLValidationPT")
@XmlSeeAlso({au.edu.unsw.soacourse.dldefinitions.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DLValidationPT {

    @WebResult(name = "ValidationMessage", targetNamespace = "http://soacourse.unsw.edu.au/dldefinitions", partName = "dlresp")
    @WebMethod(action = "http://soacourse.unsw.edu.au/dlvalidator/validate")
    public au.edu.unsw.soacourse.dldefinitions.ValidationType validate(
        @WebParam(partName = "dlreq", name = "DLInfoMessage", targetNamespace = "http://soacourse.unsw.edu.au/dldefinitions")
        au.edu.unsw.soacourse.dldefinitions.DLInputType dlreq
    );
}
