package au.edu.unsw.soacourse.dlvalidator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-30T21:10:45.250+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "DLValidatorService", 
                  wsdlLocation = "file:/C:/codes/web/DLValidatorService/src/main/resources/wsdl/dlvalidator.wsdl",
                  targetNamespace = "http://soacourse.unsw.edu.au/dlvalidator") 
public class DLValidatorService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soacourse.unsw.edu.au/dlvalidator", "DLValidatorService");
    public final static QName DLValidatorSOAP = new QName("http://soacourse.unsw.edu.au/dlvalidator", "DLValidatorSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/codes/web/DLValidatorService/src/main/resources/wsdl/dlvalidator.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DLValidatorService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/codes/web/DLValidatorService/src/main/resources/wsdl/dlvalidator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DLValidatorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DLValidatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DLValidatorService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DLValidatorService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DLValidatorService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DLValidatorService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns DLValidationPT
     */
    @WebEndpoint(name = "DLValidatorSOAP")
    public DLValidationPT getDLValidatorSOAP() {
        return super.getPort(DLValidatorSOAP, DLValidationPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DLValidationPT
     */
    @WebEndpoint(name = "DLValidatorSOAP")
    public DLValidationPT getDLValidatorSOAP(WebServiceFeature... features) {
        return super.getPort(DLValidatorSOAP, DLValidationPT.class, features);
    }

}
