package au.edu.unsw.soacourse.adrvalidator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-30T21:10:30.318+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "ADRValidatorService", 
                  wsdlLocation = "file:/C:/codes/web/ADRValidatorService/src/main/resources/wsdl/adrvalidator.wsdl",
                  targetNamespace = "http://soacourse.unsw.edu.au/adrvalidator") 
public class ADRValidatorService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soacourse.unsw.edu.au/adrvalidator", "ADRValidatorService");
    public final static QName ADRValidatorSOAP = new QName("http://soacourse.unsw.edu.au/adrvalidator", "ADRValidatorSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/codes/web/ADRValidatorService/src/main/resources/wsdl/adrvalidator.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ADRValidatorService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/codes/web/ADRValidatorService/src/main/resources/wsdl/adrvalidator.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ADRValidatorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ADRValidatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ADRValidatorService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ADRValidatorService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ADRValidatorService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ADRValidatorService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ADRValidationPT
     */
    @WebEndpoint(name = "ADRValidatorSOAP")
    public ADRValidationPT getADRValidatorSOAP() {
        return super.getPort(ADRValidatorSOAP, ADRValidationPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ADRValidationPT
     */
    @WebEndpoint(name = "ADRValidatorSOAP")
    public ADRValidationPT getADRValidatorSOAP(WebServiceFeature... features) {
        return super.getPort(ADRValidatorSOAP, ADRValidationPT.class, features);
    }

}
